name: Test find_lowest_number
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Test 1 - Generate Output from test_data/test1_input.txt
      run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt
    - name: Verify Test 1 - Compare Actual Output with Expected
      run: diff test_data/test1_expected.txt test_data/test1_actual.txt
    - name: Run Test 2 - Generate Output from test_data/test2_input.txt
      run: python find_lowest_number.py test_data/test2_input.txt test_data/test2_actual.txt
    - name: Verify Test 2 - Compare Actual Output with Expected
      run: diff test_data/test2_expected.txt test_data/test2_actual.txt
    - name: Run Test 3 - Generate Output from test_data/test3_input.txt
      run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_actual.txt
    - name: Verify Test 3 - Compare Actual Output with Expecteds
      run: diff test_data/test3_expected.txt test_data/test3_actual.txt
